name: The workflow of Iskander's project                                         # Название проекта
on: [push] # Срабатывание workflow при каждом пуше
run-name: commit ${{ github.sha }} triggered by @${{ github.actor }} # Имя для идентификации запуска - 
                                                                                 # содержит имя автора и SHA коммита

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A push was made"                                               # сообщение при каждом пуше
