name: The workflow of Iskander's project                                         # Название проекта
on: [push, pull_request] # Срабатывание workflow при каждом пуше
run-name: commit ${{ github.sha }} triggered by @${{ github.actor }} # Имя для идентификации запуска - 
                                                                                 # содержит имя автора и SHA коммита
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo on virtual machine
      uses: actions/checkout@v4
    
    
    - name: Install gtest and sphinx
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y python3-pip
        sudo apt-get install -y python3-sphinx
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Building proj
      run: g++ main.cpp test/unit_test.cpp -o main -lgtest -lgtest_main -pthread

    - name: Run tests
      run: ./main

    - name: Compile documentation
      run: sphinx build -M html /doc /doc
